fail_fast: true
default_language_version:
    python: python3.9
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.9.3"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910"
    hooks:
      - id: mypy
        exclude: ^docs/.*
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: ^docs/.*