name: epi-quark
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.16
  - matplotlib=3.3.4
  - numpy=1.20.3
  - pandas=1.3.0
  - pip=21.1.3
  - pylint=2.9.3
  - python=3.9.5
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - seaborn=0.11.1
  - sphinx=4.2.0
  - pip:
    - black==21.7b0
    - codecov
    - flake8==4.0.1
    - mypy==0.910
    - nbsphinx==0.8.7
    - pydata-sphinx-theme==0.7.1
    - pytest==6.2.4
    - pytest-cov==2.12.1
    - pytest-datadir==1.3.1
    - pytest-sugar==0.9.4