name: scoring
channels:
  - defaults
dependencies:
  - jupyterlab=2.2.6
  - numpy=1.19.1
  - pylint=2.6.0
  - python=3.8.5
  - scikit-learn=0.22.1
  - pip:
    - black==20.8b1
    - pytest==6.0.2
    - pytest-cov==2.10.1
    - pytest-sugar==0.9.4
